environment: TEST
release_notes:
  - "Note 1"
  - "Note 2"
maven_home: C:/APPLICATIONS/apache-maven-3.9.6
maven_settings: C:/Users/macasari/.m2/settingsCSI.xml
maven_compile_options:
    - "-Dpostfix=''"
    - "-DskipTests"  
maven_namespace: http://maven.apache.org/POM/4.0.0
nodejs_home: C:/Program Files/nodejs
nodejs_compile_options:
    - "--configuration=prod-rp-01" 
ant_home: C:/APPLICATIONS/apache-ant-1.6.2_ivy2
ant_target: distribution 
ant_compile_options:
    - "-Dtarget=prod-rp-01" 
projects:
  - name: mavenproject
    project_path: C:\eclipse-workspaces\csi\mavenproject
    type: Maven
    version: 1.21.0
    version_file: pom.xml
    tag: "{environment}-1.21.0-001"
    reset_type: hard
    parent_version: 1.21.0
    properties:
      - property_name: tar.version
        property_value: 1.21.0
    dependencies:
      - dependency_name: mavenproject-ear
        dependency_version: 1.21.0
      - dependency_name: mavenproject-jar
        dependency_version: 1.21.0
      - dependency_name: mavenproject-web
        dependency_version: 1.21.0      
  - name: angularproject
    project_path: C:\eclipse-workspaces\csi\angularproject
    type: Angular
    version: 1.21.0
    version_file: package.json
    tag: "{environment}-1.21.0-001"
    reset_type: hard  
  - name: antproject
    project_path: C:\eclipse-workspaces\csi\antproject
    type: Ant
    version: 1.2.2
    version_file: build.properties
    tag: "{environment}-1.21.0-001"
    reset_type: hard
