projects:
  - path: "/path/to/maven_project"
    type: "Maven"
    version_name: "project.version"
    version: "1.2.0"
    version_file: "pom.xml"
    version_file_type: "xml"
    tag: "v1.2.0"
    reset-type: "HARD"

  - path: "/path/to/ant_project"
    type: "Ant"
    version_name: "build.version"
    version: "2.1.0"
    version_file: "build.properties"
    version_file_type: "properties"
    tag: "v2.1.0"
    reset-type: "SOFT"

  - path: "/path/to/angular_project"
    type: "Angular"
    version_name: "version"
    version: "3.0.0"
    version_file: "package.json"
    version_file_type: "json"
    tag: "v3.0.0"
    reset-type: "MIXED"

