release_notes:
  - "Release 1.0.0 - Initial deployment"
  - "Release 1.1.0 - Bug fixes and improvements"

projects:
  - name: ProjectA
    folder: /path/to/projectA
    type: Maven
    property_name: version
    version: "1.1.0"
    version_file: pom.xml
    version_file_type: xml
    tag_name: v1.1.0
    reset-type: soft

  - name: ProjectB
    folder: /path/to/projectB
    type: Ant
    property_name: build.version
    version: "2.0.0"
    version_file: build.properties
    version_file_type: properties
    tag_name: v2.0.0
    reset-type: mixed

  - name: ProjectC
    folder: /path/to/projectC
    type: Angular
    property_name: version
    version: "3.1.0"
    version_file: package.json
    version_file_type: json
    tag_name: v3.1.0
    reset-type: hard


