environment: production
release_notes:
  - "Fixed major security vulnerability"
  - "Improved performance in API endpoints"

projects:
  - name: ProjectA
    folder: /path/to/projectA
    type: Maven
    version: 1.2.3
    version_file: pom.xml
    version_file_type: xml
    tag: "{environment}-release-1.2.3"
    reset-type: soft

  - name: ProjectB
    folder: /path/to/projectB
    type: Ant
    version: 2.0.1
    version_file: build.properties
    version_file_type: properties
    tag: "{environment}-release-2.0.1"
    reset-type: mixed

  - name: ProjectC
    folder: /path/to/projectC
    type: Angular
    version: 3.1.0
    version_file: package.json
    version_file_type: json
    tag: "{environment}-release-3.1.0"
    reset-type: hard
