environment: TEST
release_notes:
  - "Nota 1"
  - "Nota 2"

projects:
  - name: pbworkspace
    project_path: C:\eclipse-workspaces\csi\pbworkspace
    type: Maven
    version: 1.21.0
    version_file: pom.xml
    tag: "{environment}-1.20.0-001"
    reset-type: hard
    dependencies:
      - "pbworkspace-ear"
      - "pbworkspace-jar"
      - "pbworkspace-web"
