environment: PROD

release_notes:
  - "Note 1"
  - "Note 2"

remote_git_repo: origin
maven_home: C:/APPLICATIONS/apache-maven-3.9.6
maven_settings: C:/Users/macasari/.m2/settings.xml
maven_compile_options:
    - "-Dpostfix=''"
    - "-DskipTests"  
maven_namespace: http://maven.apache.org/POM/4.0.0
nodejs_home: C:/Program Files/nodejs
nodejs_compile_options:
    - "--configuration=prod-01" 
ant_home: C:/APPLICATIONS/apache-ant-1.6.2_ivy2
ant_target: distribution 
ant_compile_options:
    - "-Dtarget=prod-01" 
    
projects:
  - name: mavenproject
    project_path: C:\eclipse-workspaces\mavenproject
    type: Maven
    version: 1.3.3
    version_file: pom.xml
    tag: "{environment}-1.3.3-001"
    reset_type: hard
    git_branch: master
    skip: false
    parent_version: 1.3.3
    properties:
      - property_name: tar.version
        property_value: 1.3.3
    dependencies:
      - dependency_name: mavenproject-ear
        dependency_version: 1.3.3
      - dependency_name: mavenproject-jar
        dependency_version: 1.3.3
      - dependency_name: mavenproject-web
        dependency_version: 1.3.3    
        
  - name: angularproject
    project_path: C:\eclipse-workspaces\angularproject
    type: Angular
    version: 1.21.0
    version_file: package.json
    tag: "{environment}-1.21.0-001"
    reset_type: hard
    git_branch: master
    skip: false
      
  - name: antproject
    project_path: C:\eclipse-workspaces\antproject
    type: Ant
    version: 1.5.4
    version_file: build.properties
    tag: "{environment}-1.5.4-001"
    reset_type: hard
    git_branch: master
    skip: false